version: '2'
networks:
  test:
    driver: bridge
services:
  mocha:
    image: node:argon
    working_dir: /app
    command: node_modules/.bin/mocha --compilers js:babel-core/register --colors --reporter spec --slow 0 ./test/test.js
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - test
  redis:
    image: redis:latest
    networks:
      - test
